name: CI

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main]

jobs:
  terraform-lint:
    name: Terraform — fmt & validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform fmt -check -recursive
      - run: terraform init -backend=false
      - run: terraform validate
